# Default values for integration-tmc-webui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

tangodb:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-db
    tag: latest
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

databaseds:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-cpp
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

rsyslog:
  enabled: true
  image:
    registry: registry.hub.docker.com/u/
    image: jumanjiman/rsyslog
    tag: latest
    pullPolicy: IfNotPresent

itango:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: latest
    pullPolicy: IfNotPresent

tangotest:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

tmcprototype:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: tmcprototype
    tag: latest
    pullPolicy: Always

tmalarmhandler:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/tango-example
    image: tmalarmhandler
    tag: latest
    pullPolicy: Always

webjive:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: webjive-develop_webjive
    tag: latest
    pullPolicy: Always

authserver:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: webjive-develop_auth
    tag: latest
    pullPolicy: IfNotPresent

redis:
  image:
    image: redis
    tag: latest
    pullPolicy: IfNotPresent

mongodb:
  image: 
    image: mongo
    tag: 3.6-stretch
    pullPolicy: IfNotPresent

dashboards:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: webjive-develop_dashboards
    tag: latest
    pullPolicy: IfNotPresent

tangogql:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: webjive-develop_tangogql
    tag: latest
    pullPolicy: IfNotPresent

jive:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

logviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
