apiVersion: v2
appVersion: "1.0"
description: A Helm chart for deploying the HDB++ archiver for the MVP on Kubernetes
name: ska-archiver
version: 0.1.0
appVersion: 1.16.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-util
  version: 0.2.7
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tango-base
  version: 0.2.11
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: tango-base.enabled,global.sub-system.tango-base.enabled