{{ if .Values.fluentd.enabled }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd-{{ template "logging.name" . }}-{{ .Release.Name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: "{{ .Values.fluentd.image.image }}:{{ .Values.fluentd.image.tag }}"
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elastic-{{ template "logging.name" . }}-{{ .Release.Name }}"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name:  FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_ELASTICSEARCH_USER
            value: none
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: none
        volumeMounts:
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogdocker
          mountPath: /var/log/docker
          readOnly: true
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: mnt-data-logs
          mountPath: /mnt/data/docker/containers
          readOnly: true
        - name: fluentd-config-namepace
          mountPath: /fluentd/etc/conf.d
        - name: fluentd-config-fluent
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf

{{- if .Values.fluentd.livenessProbe.enabled }}
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 60
          exec:
            command:
            - '/bin/sh'
            - '-c'
            - >
              LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300};
              STUCK_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-900};
              if [ ! -e /var/log/fluentd-buffers ];
              then
                exit 1;
              fi;
              touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck;
              if [[ -z "$(find /var/log/fluentd-buffers -type f -newer /tmp/marker-stuck -print -quit)" ]];
              then
                rm -rf /var/log/fluentd-buffers;
                exit 1;
              fi;
              touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness;
              if [[ -z "$(find /var/log/fluentd-buffers -type f -newer /tmp/marker-liveness -print -quit)" ]];
              then
                exit 1;
              fi;
{{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlogdocker
        hostPath:
          path: /var/log/docker
      # In some k8s deployments the log files end up in /mnt/data/docker/containers
      - name: mnt-data-logs
        hostPath:
          path: /mnt/data/docker/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: fluentd-config-namepace
        configMap:
          name: fluentd-configmap-k8s-{{ template "logging.name" . }}-{{ .Release.Name }}
      - name: fluentd-config-fluent
        configMap:
          name: fluentd-configmap-fluent-{{ template "logging.name" . }}-{{ .Release.Name }}

{{ end }}
