{{ if .Values.kibana.enabled }}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment-{{ template "logging.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      run: kibana-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        run: kibana-{{ .Release.Namespace }}
    spec:
      containers:
      - name: kibana-{{ template "logging.name" . }}-{{ .Release.Name }}
        image: "{{ .Values.kibana.image.registry }}/{{ .Values.kibana.image.image }}:{{ .Values.kibana.image.tag }}"
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elastic-{{ template "logging.name" . }}-{{ .Release.Name }}:9200
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: SERVER_BASEPATH
          value: {{ .Values.kibana.basePath }}
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_NAME
          value: "kibana-{{ template "logging.name" . }}-{{ .Release.Name }}"
        - name: SERVER_REWRITEBASEPATH
          value: "true"
        ports:
        - name: kibana-http
          containerPort: 5601
          protocol: TCP
        readinessProbe:
          httpGet:
            path: "{{ .Values.kibana.basePath }}/api/status"
            port: 5601
          initialDelaySeconds: 5
          timeoutSeconds: 10

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-job-{{ template "logging.name" . }}-{{ .Release.Namespace }}-configurator
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: kibana-{{ template "logging.name" . }}-{{ .Release.Name }}-configurator
        image: alpine:latest
        env:
          - name: KIBANA_HOST
            value: http://kibana-{{ template "logging.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}:5601
        command: ["/bin/sh"]
        args: ["-c", "apk add curl && curl -XPOST --retry-connrefused --connect-timeout 5 --retry 999  --retry-delay 1 \"${KIBANA_HOST}\"/kibana/api/saved_objects/index-pattern/ska_logs -H \"kbn-xsrf: true\" -H \"Content-Type: application/json\" -d @/tmp/kibana_conf.json "]
        volumeMounts:
          - name: kibana-config
            mountPath: /tmp/
            readOnly: true
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-configmap-{{ template "logging.name" . }}-{{ .Release.Name }}
      restartPolicy: "Never"

{{ end }}
