apiVersion: v2
appVersion: "1.0"
description: A Helm chart for deploying the DSH LMC prototype on Kubernetes
name: dsh-lmc-prototype
version: 0.0.1
home: https://gitlab.com/ska-telescope/dsh-lmc-prototype/
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
sources:
- https://gitlab.com/ska-telescope/dsh-lmc-prototype/
