{{ if .Values.databaseds.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: databaseds-{{ template "integration-tmc-webui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: databaseds-{{ template "integration-tmc-webui.name" . }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: ds
    port: 10000
  clusterIP: None
  selector:
    app: databaseds-{{ template "integration-tmc-webui.name" . }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "databaseds-{{ template "integration-tmc-webui.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: databaseds-{{ template "integration-tmc-webui.name" . }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: databaseds-{{ template "integration-tmc-webui.name" . }}
  serviceName: databaseds-{{ template "integration-tmc-webui.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: databaseds-{{ template "integration-tmc-webui.name" . }}
        chart: {{ template "integration-tmc-webui.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: databaseds
        image: "{{ .Values.databaseds.image.registry }}/{{ .Values.databaseds.image.image }}:{{ .Values.databaseds.image.tag }}"
        imagePullPolicy: {{ .Values.databaseds.image.pullPolicy }}
        command:
          - /usr/local/bin/wait-for-it.sh
          - tangodb-{{ template "integration-tmc-webui.name" . }}:3306
          - --timeout=30
          - --strict
          - --
          - /usr/local/bin/DataBaseds
          - "2"
          - -ORBendPoint
          - giop:tcp::10000
        env:
          - name: MYSQL_HOST
            value: tangodb-{{ template "integration-tmc-webui.name" . }}:3306
          - name: MYSQL_DATABASE
            value: "{{ .Values.tangodb.db.db }}"
          - name: MYSQL_USER
            value: "{{ .Values.tangodb.db.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.tangodb.db.password }}"
          - name: TANGO_HOST
            value: databaseds-{{ template "integration-tmc-webui.name" . }}:10000
        ports:
        - name: ds
          containerPort: 10000
        resources:
{{ toYaml .Values.databaseds.resources | indent 10 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}