{{ if .Values.tmcprototype.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: tmcalarm-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tmcalarm-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}
    chart: {{ template "integration-tmc-webui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  initContainers:
  - name: waitdatabaseds
    image: nexus.engageska-portugal.pt/ska-docker/tango-itango:latest
    imagePullPolicy: IfNotPresent
    command:
    - /usr/local/bin/wait-for-it.sh
    - databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000
    - --timeout=30
    - --strict
    - --
    - echo "Databaseds ready for use."

  containers:
  - name: tm-alarmhandler
    image: "{{ .Values.tmalarmhandler.image.registry }}/{{ .Values.tmalarmhandler.image.image }}:{{ .Values.tmalarmhandler.image.tag }}"
    imagePullPolicy: {{ .Values.tmalarmhandler.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "./app/alarmhandler-srv 01"
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000

  - name: configure-alarms
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "/venv/bin/python /app/tmcprototype/TMAlarmHandler/configure_alarms.py"
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000

  - name: conf-polling-events
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "/venv/bin/python /app/tmcprototype/configurePollingAndEvents.py"
    env:
    - name: TANGO_HOST
      value: databaseds-{{ template "integration-tmc-webui.name" . }}-{{ .Release.Name }}:10000

{{- with .Values.tmcprototype.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}