{{ if .Values.tangodb.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.tangodb.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.tangodb.component }}
    function: {{ .Values.tangodb.function }}
    domain: {{ .Values.tangodb.domain }}
    intent: {{ .Values.tangodb.intent }}
spec:
  ports:
  - name: mysql
    port: 3306
  type: NodePort
  selector:
    app: {{ template "tango-base.name" . }}
    component: {{ .Values.tangodb.component }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tango-base.name" . }}-{{ .Values.tangodb.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tango-base.labels" . | indent 4 }}
    component: {{ .Values.tangodb.component }}
    function: {{ .Values.tangodb.function }}
    domain: {{ .Values.tangodb.domain }}
    intent: {{ .Values.tangodb.intent }}
spec:
  selector:
    matchLabels:
      app: {{ template "tango-base.name" . }}
      component: {{ .Values.tangodb.component }}
  serviceName: {{ template "tango-base.name" . }}-{{ .Values.tangodb.component }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "tango-base.labels" . | indent 8 }}
        component: {{ .Values.tangodb.component }}
        function: {{ .Values.tangodb.function }}
        domain: {{ .Values.tangodb.domain }}
        intent: {{ .Values.tangodb.intent }}
    spec:
      containers:
      - name: tangodb
        image: "{{ .Values.tangodb.image.registry }}/{{ .Values.tangodb.image.image }}:{{ .Values.tangodb.image.tag }}"
        imagePullPolicy: {{ .Values.tangodb.image.pullPolicy }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ .Values.tangodb.db.rootpw }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.tangodb.db.db }}"
          - name: MYSQL_USER
            value: "{{ .Values.tangodb.db.user }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.tangodb.db.password }}"
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "1"
        ports:
        - name: mysql
          containerPort: 3306
{{ if .Values.tangodb.use_pv }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
{{ end }}
        resources:
{{ toYaml .Values.tangodb.resources | indent 10 }}
      volumes:
{{ if .Values.tangodb.use_pv }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "tango-base.name" . }}-tangodb-storage
{{ end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{ end }}