{{ if .Values.tmcprototype.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "tmc-proto-configuration-json-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data: 
  configuration.json: 
{{ (tpl (.Files.Glob "data/configuration.json").AsConfig . ) | indent 2  }}

---
apiVersion: v1
kind: Pod
metadata:
  name: tmcprototype-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tmcprototype-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}
    chart: {{ template "tmc-proto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumes:
  - name: configuration
    configMap:
      name: "tmc-proto-configuration-json-{{ template "tmc-proto.name" . }}-{{ .Release.Name }}"

  initContainers:
  - name: dsconfig
    image: "{{ .Values.dsconfig.image.registry }}/{{ .Values.dsconfig.image.image }}:{{ .Values.dsconfig.image.tag }}"
    imagePullPolicy: {{ .Values.dsconfig.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - databaseds-tango-base-{{ .Release.Name }}:10000
      - --timeout=30
      - --strict
      - --
      - json2tango -w -a -u data/configuration.json
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000
    volumeMounts:
      - name: configuration
        mountPath: data
        readOnly: true

  containers:
  - name: dishmaster1
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - " /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishmaster2
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "/venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 02"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishmaster3
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "/venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 03"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishmaster4
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "/venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 04"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishleafnode1
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_d0001/elt/master &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishleafnode2
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - " retry --max=10 -- tango_admin --ping-device mid_d0002/elt/master &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 02"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishleafnode3
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_d0003/elt/master &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 03"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: dishleafnode4
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_d0004/elt/master &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 04"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspsubarrayleafnode1
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/subarray_01 &&\
             /venv/bin/python /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspsubarrayleafnode2
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/subarray_02 &&\
             /venv/bin/python /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 02"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspsubarrayleafnode3
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/subarray_03 &&\
             /venv/bin/python /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 03"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: cspmasterleafnode
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp/elt/master &&\
             /venv/bin/python /app/tmcprototype/CspMasterLeafNode/CspMasterLeafNode/CspMasterLeafNode.py 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: sdpsubarrayleafnode1
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_sdp/elt/subarray_1 &&\
             /venv/bin/python /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: sdpsubarrayleafnode2
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_sdp/elt/subarray_2 &&\
             /venv/bin/python /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 02"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: sdpsubarrayleafnode3
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_sdp/elt/subarray_3 &&\
             /venv/bin/python /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 03"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: sdpmasterleafnode
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_sdp/elt/master &&\
             /venv/bin/python /app/tmcprototype/SdpMasterLeafNode/SdpMasterLeafNode/SdpMasterLeafNode.py 01 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: subarraynode1
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0001 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0002 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0003 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0004 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray01 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray01 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa1"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: subarraynode2
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0001 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0002 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0003 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0004 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray02 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray02 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa2"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: subarraynode3
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0001 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0002 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0003 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0004 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray03 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray03 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa3"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: centralnode
    image: "{{ .Values.tmcprototype.image.registry }}/{{ .Values.tmcprototype.image.image }}:{{ .Values.tmcprototype.image.tag }}"
    imagePullPolicy: {{ .Values.tmcprototype.image.pullPolicy }}

    command:
      - sh
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_master &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_master &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_subarray_node/1 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_subarray_node/2 &&\
             retry --max=10 -- tango_admin --ping-device ska_mid/tm_subarray_node/3 &&\
             /venv/bin/python /app/tmcprototype/CentralNode/CentralNode/CentralNode.py 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

  - name: tm-alarmhandler
    image: "{{ .Values.tmalarmhandler.image.registry }}/{{ .Values.tmalarmhandler.image.image }}:{{ .Values.tmalarmhandler.image.tag }}"
    imagePullPolicy: {{ .Values.tmalarmhandler.image.pullPolicy }}
    command:
      - sh
    args:
      - -c
      - "./app/alarmhandler-srv 01"
    env:
    - name: TANGO_HOST
      value: databaseds-tango-base-{{ .Release.Name }}:10000

{{- with .Values.tmcprototype.env }}
{{ toYaml . | indent 4 }}
{{- end }}
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}

