apiVersion: v1
appVersion: "1.0"
name: sdp-prototype
description: Helm chart to deploy the SDP Prototype
version: 0.4.0
home: https://developer.skatelescope.org/projects/sdp-prototype/
sources:
- https://gitlab.com/ska-telescope/sdp-prototype
icon: http://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
- name: Peter Wortmann
  email: pw410@cam.ac.uk
- name: vla22
  email: vla22@mrao.cam.ac.uk
- name: Mark Ashdown
  email: maja1@mrao.cam.ac.uk
