# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


elastic:
  enabled: true
  use_pv: true # Make use of a persistent volume
  image:
    registry: docker.elastic.co
    image: elasticsearch/elasticsearch
    tag: 7.4.2
    pullPolicy: IfNotPresent
  ilm:
    rollover:
      max_size: "1gb"
      max_age: "1d"
    delete:
      min_age: "1d"

fluentd:
  enabled: true
  image:
    image: fluent/fluentd-kubernetes-daemonset
    tag: v1.7-debian-elasticsearch7-2
    pullPolicy: IfNotPresent
  livenessProbe:
    enabled: true
  logging_rate_throttle:
    enabled: true
    # group_reset_rate_s must be <= group_bucket_limit
    # group_reset_rate_s must be <= group_bucket_limit / group_bucket_period_s
    group_bucket_period_s: 60
    group_bucket_limit: 1000
    group_reset_rate_s: 10

kibana:
  enabled: true
  image:
    registry: docker.elastic.co
    image: kibana/kibana
    tag: 7.4.2
    pullPolicy: IfNotPresent
  basePath: /kibana

ingress:
  enabled: true
  nginx: true
  hostname: integration.engageska-portugal.pt

tests:
  enabled: true
  image:
    image: ska-docker/ska-python-buildenv
    registry: nexus.engageska-portugal.pt
    tag: 0.1.0
    pullPolicy: IfNotPresent

demo_mode:
  enabled: false
