---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sdp-subarray
  namespace: {{ .Release.Namespace }}
  labels:
    app: sdp-subarray-{{ .Release.Name }}
    chart: {{ template "sdp-prototype.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sdp-subarray
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sdp-subarray
        chart: {{ template "sdp-prototype.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - env:
        - name: TANGO_HOST
          value: databaseds-tango-base-{{ .Release.Name }}:10000
        image: nexus.engageska-portugal.pt/sdp-prototype/tangods_sdp_subarray:latest
        imagePullPolicy: Always
        name: subarray
        resources: {}
