apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-prototype.fullname" . }}-workflow-testdeploy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "sdp-prototype.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.workflow.testdeploy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sdp-prototype.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      {{ include "sdp-prototype.wait-for-etcd" . | nindent 6 }}
      containers:
      - image: {{ .Values.workflow.testdeploy.container }}:{{ .Values.workflow.testdeploy.version }}
        name: {{ .Chart.Name }}
        env:
        - name: SDP_CONFIG_HOST
          value: {{ include "sdp-prototype.fullname" . }}-etcd-client.default.svc.cluster.local
        {{- with .Values.workflow.testdeploy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- if index .Values "workflow" "testdeploy" "direct-kube-deploy" }}
      serviceAccountName: {{ include "sdp-prototype.fullname" . }}-testdeploy
{{- end }}
