{{ if .Values.ssh.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.ssh.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.ssh.component }}
    function: {{ .Values.ssh.function }}
    domain: {{ .Values.ssh.domain }}
    intent: production
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      nodePort: {{ .Values.ssh.nodePort }}
  selector:
    app: {{ template "oet.name" . }}
    component: {{ .Values.ssh.component }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.ssh.component }}-env-settings
  namespace: {{ .Release.Namespace }}
data:
  environment: |
    TANGO_HOST={{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
    OET_REST_URI=http://{{ template "oet.name" . }}-rest:5000/api/v1.0/procedures
  profile: |
    export PATH=/venv/bin:${PATH}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "oet.name" . }}-{{ .Values.ssh.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oet.labels" . | indent 4 }}
    component: {{ .Values.ssh.component }}
    function: {{ .Values.ssh.function }}
    domain: {{ .Values.ssh.domain }}
    intent: production
spec:
  selector:
    matchLabels:
      app: {{ template "oet.name" . }}
      component: {{ .Values.ssh.component }}
  serviceName: ssh-{{ template "oet.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "oet.labels" . | indent 8 }}
        component: {{ .Values.ssh.component }}
        function: {{ .Values.ssh.function }}
        domain: {{ .Values.ssh.domain }}
        intent: production
    spec:
      restartPolicy: Always
      initContainers:
      - name: check-databaseds-ready
        image: "{{ .Values.ssh.image.registry }}/{{ .Values.ssh.image.image }}:{{ .Values.ssh.image.tag }}"
        command:
          - /usr/local/bin/wait-for-it.sh
          - {{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
          - --timeout=30
          - --strict
          - --
          - echo databaseds ready
      containers:
      - name: oet-ssh
        image: "{{ .Values.ssh.image.registry }}/{{ .Values.ssh.image.image }}:{{ .Values.ssh.image.tag }}"
        imagePullPolicy: {{ .Values.ssh.image.pullPolicy }}
        ports:
          - name: oet-ssh
            containerPort: 22
        env:
          - name: TANGO_HOST
            value: {{ if .Values.tangoDatabaseDS -}} {{ .Values.tangoDatabaseDS }}:10000 {{- else -}} databaseds-tango-base-{{ .Release.Name }}:10000 {{- end }}
        volumeMounts:
          - name: env-settings
            mountPath: /home/tango/.profile
            subPath: .profile
          - name: env-settings
            mountPath: /etc/environment
            subPath: environment
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: {{ .Values.ssh.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ssh.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.ssh.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.ssh.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.ssh.readinessProbe.failureThreshold }}
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: {{ .Values.ssh.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ssh.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.ssh.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.ssh.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.ssh.livenessProbe.failureThreshold }}
      volumes:
        - name: env-settings
          configMap:
            name: {{ template "oet.name" . }}-{{ .Values.ssh.component }}-env-settings
            items:
            - key: environment
              path: environment
            - key: profile
              path: .profile
      resources:
  {{ toYaml .Values.ssh.resources | indent 10 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{ end }}
