apiVersion: v2
name: skampi
description: A Helm chart for deploying the skampi collection
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
