# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

tangodb:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-db
    tag: latest
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

databaseds:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-cpp
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

itango:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: latest
    pullPolicy: IfNotPresent

tangotest:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

jive:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

vnc:
  enabled: true
  nodeport_vnc: 32081
  nodeport_novnc: 32082
  replicas: 3
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-vnc
    tag: latest
    pullPolicy: IfNotPresent

vscode:
  enabled: true
  nodeport: 32080
  replicas: 3
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-vscode
    tag: 0.1.2
    pullPolicy: IfNotPresent

tangorest:
  enabled: true
  replicas: 1
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-rest
    tag: latest
    pullPolicy: IfNotPresent

logviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

# Configure Ingress resource that allow you to access the Tango REST API
ingress:
  enabled: true
  hostname: tango-base.minikube.local

  # Ingress annotations
  annotations:
    kubernetes.io/ingress.class: traefik

  # Ingress TLS configuration
  #
  tls:
    enabled: false
    secretname: "tls-secret-tango-base-{{ .Release.Name }}"
    hostname: "{{ .Values.ingress.hostname }}"


nodeSelector: {}

affinity: {}

tolerations: []
