apiVersion: v2
name: mvp-low
description: A Helm chart for Kubernetes MVP Low
type: application
version: 0.5.0
appVersion: 0.5.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-base
  version: 0.2.23
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-util
  version: 0.2.14
  repository: https://artefact.skao.int/repository/helm-internal
- name: sdp
  version: 0.4.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: sdp.enabled
- name: ska-tmc-low
  version: 0.3.6
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-low-mccs
  version: 0.8.2
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: ska-webjive
  version: 1.0.24
  repository: https://artefact.skao.int/repository/helm-internal
- name: skuid
  version: 0.2.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: skuid.enabled
- name: ska-oso-scripting
  version: 0.5.1
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-oso-scripting.enabled
- name: landingpage
  version: 0.1.0
  repository: file://../landingpage
  condition: landingpage.enabled
- name: ska-archiver
  version: 0.1.8
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-archiver.enabled

