apiVersion: v2
name: mvp-low
description: A Helm chart for Kubernetes MVP Low
type: application
version: 0.5.0
appVersion: 0.5.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-base
  version: 0.2.20
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tango-util
  version: 0.2.13
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: sdp
  version: 0.4.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: sdp.enabled
- name: tmc-low
  version: 0.1.9
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: ska-low-mccs
  version: 0.6.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: webjive
  version: 1.0.18
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: skuid
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: skuid.enabled
- name: oet-scripts
  version: 0.3.8
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: oet-scripts.enabled
- name: landingpage
  version: 0.1.0
  repository: file://../landingpage
  condition: landingpage.enabled
- name: ska-archiver
  version: 0.1.4
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: ska-archiver.enabled

