apiVersion: v1
appVersion: "1.0"
name: sdp-prototype
description: helm chart to deploy the SDP Prototype on Kubernetes
version: 0.2.1
home: https://developer.skatelescope.org/projects/sdp-prototype/
sources:
- https://github.com/ska-telescope/sdp-prototype
icon: http://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
maintainers:
- name: Peter Wortmann
  email: pw410@cam.ac.uk
- name: vla22
  email: vla22@mrao.cam.ac.uk
- name: Benjamin Mort
  email: ben.mort@gmail.com
