kind: ConfigMap
apiVersion: v1
metadata:
  name: chartinfo-{{ .Release.Name }}
data:
  chartinfo.js: |-
    const CHARTINFO = {
        name: '{{ .Chart.Name }}',
        version: '{{ .Chart.Version }}',
        dependencies: [
        {{- range  .Chart.Dependencies }}
        { name: '{{ .Name }}' , version: '{{ .Version }}' },
        {{- end }}
        ]
    }
